spring:
  application:
    name: landing-saveform-service
  profiles:
    active: dev
  jackson:
    default-property-inclusion: NON_NULL
    
springdoc:
  swagger-ui:
    path: /docs/swagger-ui.html
